/* ========== Creacion de ordenes ================= */
const POST_ORDER = "POST_ORDER"; //ENVIA LA ORDEN A LA BD
const TOTAL_ORDER = "TOTAL_ORDER"; //Actualiza el total de la orden de compra
const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
const CART_EMPTY = "CART_EMPTY";
const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
const ORDER_COMPLETE_PAY = "ORDER_COMPLETE_PAY";
const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";

module.exports = {
  POST_ORDER,
  TOTAL_ORDER,
  ORDER_CREATE_REQUEST,
  ORDER_CREATE_SUCCESS,
  CART_EMPTY,
  ORDER_CREATE_FAIL,
  ORDER_COMPLETE_PAY,
  GET_ORDERS_SUCCESS,
  GET_ORDERS_FAIL,
  GET_ORDERS_REQUEST,
};
